# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 20:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('risk_level', models.CharField(max_length=100)),
                ('test_done', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('next_visit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FourthVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('risk_level', models.CharField(max_length=100)),
                ('test_done', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('next_visit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('sub_location', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MidWife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('home_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('home_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('first_visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.FirstVisit')),
                ('fourth_visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.FourthVisit')),
            ],
        ),
        migrations.CreateModel(
            name='SecondVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('risk_level', models.CharField(max_length=100)),
                ('test_done', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('next_visit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SupportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meeting_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.MidWife')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('risk_level', models.CharField(max_length=100)),
                ('test_done', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('next_visit', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='mother',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.SupportGroup'),
        ),
        migrations.AddField(
            model_name='mother',
            name='home_health_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.HealthFacility'),
        ),
        migrations.AddField(
            model_name='mother',
            name='second_visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.SecondVisit'),
        ),
        migrations.AddField(
            model_name='mother',
            name='third_visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.ThirdVisit'),
        ),
    ]
