# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20170304_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthfacility',
            options={'permissions': (('Manage Hospital', 'Can Manage a Hospital and its data '),)},
        ),
    ]
