# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20170306_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthfacility',
            options={},
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
