# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_healthfacility_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
