# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20170307_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroup',
            name='health_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.HealthFacility'),
        ),
    ]
