# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_supportgroup_health_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroup',
            name='year_formed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
